// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFWE9OXu_qm2TQeDhADRIqMIGHRjR1Xs',
    appId: '1:168518598651:web:6aec60db7289089a57555e',
    messagingSenderId: '168518598651',
    projectId: 'flutter-musicplayer-ec881',
    authDomain: 'flutter-musicplayer-ec881.firebaseapp.com',
    storageBucket: 'flutter-musicplayer-ec881.appspot.com',
    measurementId: 'G-Z3D1VD15BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANbBC_T2UjgvtzzFJ8IAV2ZDASj4axIcs',
    appId: '1:168518598651:android:129ccf0424af7d2f57555e',
    messagingSenderId: '168518598651',
    projectId: 'flutter-musicplayer-ec881',
    storageBucket: 'flutter-musicplayer-ec881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2D_Tc-loHRHV4uF3eMSx3a_X1mvMjMz8',
    appId: '1:168518598651:ios:f93fe941fb16eb2157555e',
    messagingSenderId: '168518598651',
    projectId: 'flutter-musicplayer-ec881',
    storageBucket: 'flutter-musicplayer-ec881.appspot.com',
    iosBundleId: 'com.example.flutterMusicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2D_Tc-loHRHV4uF3eMSx3a_X1mvMjMz8',
    appId: '1:168518598651:ios:f93fe941fb16eb2157555e',
    messagingSenderId: '168518598651',
    projectId: 'flutter-musicplayer-ec881',
    storageBucket: 'flutter-musicplayer-ec881.appspot.com',
    iosBundleId: 'com.example.flutterMusicplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiFWE9OXu_qm2TQeDhADRIqMIGHRjR1Xs',
    appId: '1:168518598651:web:587d402982740feb57555e',
    messagingSenderId: '168518598651',
    projectId: 'flutter-musicplayer-ec881',
    authDomain: 'flutter-musicplayer-ec881.firebaseapp.com',
    storageBucket: 'flutter-musicplayer-ec881.appspot.com',
    measurementId: 'G-T6PK6M5WVJ',
  );
}
